config/routes.rb
Harmony::Application.routes.draw do

  devise_for :users, :path_names => { :sign_in => 'login', :sign_out => 'logout' }

  resource :profile

  resources :lists do 
    resources :items    
  end  
 
  resources :accounts do
    post 'join', :on => :member
    resources :lists
    resources :notes
    resources :todos do
      member do
        get 'complete'
        get 'hide'
      end
    end
 end

  #match 'accounts/:account_id/todos/:id/complete' => 'todos#complete', :as => :complete_todo
  #match 'accounts/:id/join' => 'accounts#join', :as => :join_account

  match '/' => 'home#index', :as => :home
  root :to => 'home#index'

end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :account
  has_many :items

  attr_protected :account_id 

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  before_filter :get_account
  before_filter :auth_check

  def show
    respond_to do |format|
      format.html { redirect_to @account }
    end
  end

  def new
    @list = List.new

    respond_to do |format|
      format.html # new.html.erb
      format.js { render :layout => false }
    end
  end

  def edit
    @list = List.find(params[:id])
  end

  def create
    @list = List.new(params[:list])

    respond_to do |format|
      if @list.save
        @account.lists << @list
        UserMailer.new_list(@account.friend(current_user), current_user, @account).deliver
        Event.create!(:event_type => :new_list, :user => current_user, :account => @account)
        format.html { redirect_to(@account, :notice => 'List was successfully created.') }
      else
        format.html { render :action => "new" }
      end
    end
  end

  def update
    @list = List.find(params[:id])

    respond_to do |format|
      if @list.update_attributes(params[:list])
        format.html { redirect_to(@account, :notice => 'List was successfully updated.') }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy

    respond_to do |format|
      format.html { redirect_to(@account) }
    end
  end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.haml
.form
  = form_for @list, :url => account_lists_path(@account) do |f|
    - if @list.errors.any?
      #errorExplanation
        %h2= "#{pluralize(@list.errors.count, 'error')} prohibited this user from being saved:"
        %ul
        - @list.errors.full_messages.each do |msg|
          %li= msg
    .label= f.label :title
    .field= f.text_field :title
    = f.submit :class => :button
  %br.clear

app/views/lists/_list.html.haml
.lists
  = list.title
  = link_to '+', new_list_item_path(list), :rel => 'facebox'
  %ul
    = render :partial => 'items/item', :collection => list.items, :locals => {:hide => false}

app/views/lists/edit.html.haml
= render 'form'

app/views/lists/index.html.haml
%h1= t('.title')
%p= link_to t('.new_list'), new_list_path

%table
  %thead
    %tr
      %th= List.human_attribute_name :title
      %th= List.human_attribute_name :account_id
      %th{:colspan => 3}= t 'actions'
  
  %tbody
    - for list in @lists
      %tr{ :class => cycle(:odd, :even) }
        %td= list.title
        %td= list.account_id
        %td.action= link_to t('show'), list
        %td.action= link_to t('edit'), edit_list_path(list)
        %td.action= link_to t('destroy'), list, :confirm => t('are_you_sure'), :method => :delete

app/views/lists/show.html.haml
%h1= t '.title'
%p
  = link_to t('back'), lists_path
  = link_to t('edit'), edit_list_path(@list)

%dl
  %dt= List.human_attribute_name :title
  %dd= @list.title
  %dt= List.human_attribute_name :account_id
  %dd= @list.account_id