config/routes.rb
Harmony::Application.routes.draw do

  devise_for :users, :path_names => { :sign_in => 'login', :sign_out => 'logout' }

  resource :profile

  resources :lists do 
    resources :items    
  end  
 
  resources :accounts do
    post 'join', :on => :member
    resources :lists
    resources :notes
    resources :todos do
      member do
        get 'complete'
        get 'hide'
      end
    end
 end

  #match 'accounts/:account_id/todos/:id/complete' => 'todos#complete', :as => :complete_todo
  #match 'accounts/:id/join' => 'accounts#join', :as => :join_account

  match '/' => 'home#index', :as => :home
  root :to => 'home#index'

end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :user
  belongs_to :account
  has_one :event, :dependent => :destroy

  validates_presence_of :content

  attr_protected :account_id, :user_id

  def feed_text
    "#{self.user.name} says: \"#{event.note ? event.note.content : 'NO NOTE'}\"."
  end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
 
  before_filter :get_account
  before_filter :auth_check 

  def new
    @note = Note.new

    respond_to do |format|
      format.html
      format.js { render :layout => false } 
    end
  end

  def edit
    @note = Note.find(params[:id])
  end

  def create
    @note = Note.new(params[:note])

    respond_to do |format|
      if @note.save
        @account.notes << @note
        current_user.notes << @note 
        Event.create!(:event_type => :new_note, :user => current_user, :account => @account, :note => @note)
        UserMailer.new_note(@account.friend(current_user), current_user, @account).deliver
        format.html { redirect_to(@account, :notice => 'Note was successfully created.') }
      else
        format.html { render :action => "new" }
      end
    end
  end

  def update
    @note = Note.find(params[:id])

    respond_to do |format|
      if @note.update_attributes(params[:note])
        format.html { redirect_to(@account, :notice => 'Note was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  def destroy
    @note = Note.find(params[:id])
    @note.destroy

    respond_to do |format|
      format.html { redirect_to(@account) }
    end
  end
 
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.haml
.form
  = form_for @note, :url => account_notes_path(@account) do |f|
    - if @note.errors.any?
      #errorExplanation
        %h2= "#{pluralize(@note.errors.count, 'error')} prohibited this user from being saved:"
        %ul
        - @note.errors.full_messages.each do |msg|
          %li= msg
    .label= f.label :content, "Message"
    .field= f.text_field :content
    = f.submit :class => :button
  %br.clear

app/views/notes/_note.html.haml
.note
  .right
    = button_to "X", account_note_path(@account, note), :confirm => "Are you sure?", 
      :method => :delete, :class => 'link_button'
    = link_to "Edit Note", edit_account_note_path(@account, note), :class => 'link_button'
  %span
    From: #{note.user.name }
  %p= note.content

app/views/notes/edit.html.haml
.form
  = form_for @note, :url => account_note_path(@account, @note) do |f|
    - if @note.errors.any?
      #errorExplanation
        %h2= "#{pluralize(@note.errors.count, 'error')} prohibited this user from being saved:"
        %ul
        - @note.errors.full_messages.each do |msg|
          %li= msg
    .label= f.label :content, "Message"
    .field= f.text_field :content
    = f.submit :class => :button
  %br.clear

app/views/notes/index.html.haml
%h1= t('.title')

%table
  %thead
    %tr
      %th= Note.human_attribute_name :user_id
      %th= Note.human_attribute_name :account_id
      %th= Note.human_attribute_name :content
      %th{:colspan => 3}= t 'actions'
  
  %tbody
    - for note in @notes
      %tr{ :class => cycle(:odd, :even) }
        %td= note.user_id
        %td= note.account_id
        %td= note.content

app/views/notes/new.html.haml
.form
  = form_for @note, :url => account_notes_path(@account) do |f|
    - if @note.errors.any?
      #errorExplanation
        %h2= "#{pluralize(@note.errors.count, 'error')} prohibited this user from being saved:"
        %ul
        - @note.errors.full_messages.each do |msg|
          %li= msg
    .label= f.label :content, "Message"
    .field= f.text_field :content
    = f.submit :class => :button
  %br.clear

app/views/notes/show.html.haml
%h1= t '.title'
%p
  = link_to t('back'), notes_path
  = link_to t('edit'), edit_note_path(@note)

%dl
  %dt= Note.human_attribute_name :user_id
  %dd= @note.user_id
  %dt= Note.human_attribute_name :account_id
  %dd= @note.account_id
  %dt= Note.human_attribute_name :content
  %dd= @note.content