config/routes.rb
Harmony::Application.routes.draw do

  devise_for :users, :path_names => { :sign_in => 'login', :sign_out => 'logout' }

  resource :profile

  resources :lists do 
    resources :items    
  end  
 
  resources :accounts do
    post 'join', :on => :member
    resources :lists
    resources :notes
    resources :todos do
      member do
        get 'complete'
        get 'hide'
      end
    end
 end

  #match 'accounts/:account_id/todos/:id/complete' => 'todos#complete', :as => :complete_todo
  #match 'accounts/:id/join' => 'accounts#join', :as => :join_account

  match '/' => 'home#index', :as => :home
  root :to => 'home#index'

end

app/models/todo.rb
class Todo < ActiveRecord::Base
  belongs_to :account
  has_and_belongs_to_many :users

  attr_protected :account_id
  
  validates_presence_of :task
  validates_presence_of :todo_type 

  class << self
   def unfinished
     where(:completed => false).order('created_at desc')
   end
   def finished
     where(:completed => true, :hidden => false).order('updated_at desc')
   end
   def for_user(user)
     joins('left outer join todos_users on todos.id=todos_users.todo_id').where('todos_users.user_id = ?', user.id)
   end
  end

  def done? 
    self.users == [] 
  end 

  def check_off(user)
    self.users.delete user if self.users.include? user 
    self.users = [] if self.todo_type == 'either'
    self.toggle!(:completed) if done? && !completed?
  end 

  def hide
    self.hidden = true
    self.save
  end

  def add_unfinished_users(user, friend)
    case self.todo_type
    when 'me'
      self.users = [user]
    when 'you'
      self.users = [friend]
    when 'we'
      self.users = [user, friend]
    when 'either'
      self.users = [user, friend]
    end 
    self.save 
  end

end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

  before_filter :get_account
  before_filter :auth_check

  def show
    @todo = Todo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  def new
    @todo = Todo.new

    respond_to do |format|
      format.html # new.html.erb
      format.js { render :layout => false }
    end
  end

  def edit
    @todo = Todo.find(params[:id])
  end

  def create
    @todo = Todo.new(:task => params[:todo][:task], :todo_type => params[:todo][:todo_type])

    respond_to do |format|
      if @todo.save
        @todo.add_unfinished_users(current_user, @account.friend(current_user))
        @account.todos << @todo
        UserMailer.new_todo(@account.friend(current_user), current_user, @account).deliver
        Event.create!(:event_type => :new_todo, :user => current_user, :account => @account)
        format.html { redirect_to(@account, :notice => 'Todo was successfully created.') }
      else
        format.html { render :action => "new" }
      end
    end
  end

  def update
    @todo = Todo.find(params[:id])
    task = params[:todo][:task]
    type = params[:todo][:todo_type]

    respond_to do |format|
      if @todo.update_attributes(:task => task, :todo_type => type)
        @todo.add_unfinished_users(current_user, @account.friend(current_user))
        format.html { redirect_to(@account, :notice => 'Todo was successfully updated.') }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  def complete
    @todo = Todo.find(params[:id])
    email = UserMailer.completed_todo(@account.friend(current_user), current_user, @todo)
    @todo.check_off(current_user)
    if @todo.done?
      email.deliver
    end 

    respond_to do |format|
      format.html { redirect_to(@account) }
      format.js { render :layout => false }
    end
  end

  def hide
    @todo = Todo.find(params[:id])
    @account = Account.find(params[:account_id])
    @todo.hide

    respond_to do |format|
      format.html { redirect_to(@account) }
      format.js { render :layout => false }
    end
  end

  private 

  
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/todos/_form.html.haml
.form
  = form_for @todo, :url => account_todos_path(@account) do |f|
    - if @todo.errors.any?
      #errorExplanation
        %h2= "#{pluralize(@todo.errors.count, 'error')} prohibited this user from being saved:"
        %ul
        - @todo.errors.full_messages.each do |msg|
          %li= msg
    = f.radio_button :todo_type, :me 
    = f.label :todo_type_me, "I need to do this." 
    = f.radio_button :todo_type, :you 
    = f.label :todo_type_you, "#{@account.friend(current_user).name} needs to do this." 
    %br
    = f.radio_button :todo_type, :we 
    = f.label :todo_type_we, "Both of us." 
    = f.radio_button :todo_type, :either
    = f.label :todo_type_either, "Either of us." 

    .field= f.text_field :task
    = f.submit :class => :button
  %br.clear

app/views/todos/_jstodo.html.haml
- if todo.users.include? current_user
  .todo.unfinished{:id => "todo_#{todo.id}", :style => "display: none;"}
    = link_to "Done", complete_account_todo_path(@account, todo), :class => 'link_button right get'
    You need to #{todo.task}.
- elsif todo.users.blank?
  .todo.finished{:id => "todo_#{todo.id}", :style => "display: none;"}
    .hide= link_to '[ Hide ]', hide_account_todo_path(@account, todo), :class => 'link_button right get'
    #{todo.task} 
- else
  .todo.pending
    #{@account.friend(current_user).name.split[0]} still needs to #{todo.task}. 

app/views/todos/_todo.html.haml
- if todo.users.include? current_user
  .todo.unfinished{:id => "todo_#{todo.id}", :style => hide ? 'display: none;' : '' }
    = link_to "Done", complete_account_todo_path(@account, todo), :class => 'link_button right get'
    You need to #{todo.task}.
- elsif todo.users.blank?
  .todo.finished{:id => "todo_#{todo.id}", :style => hide ? 'display: none;' : '' }
    .hide= link_to '[ Hide ]', hide_account_todo_path(@account, todo), :class => 'link_button right get'
    #{todo.task}
- else
  .todo.pending{:id => "todo_#{todo.id}", :style => hide ? 'display: none;' : '' }
    #{@account.friend(current_user).name.split[0]} still needs to #{todo.task}. 

app/views/todos/complete.js.erb
$('<%= "#todo_#{@todo.id}" %>').fadeOut('slow', function() {
  $('<%= "#todo_#{@todo.id}" %>').remove();

  $('<%= escape_javascript(render :partial => 'todos/todo', :locals => {:todo => @todo, :hide => true} ) %>').prependTo('<%= @todo.done? ? "#finished" : "#theirs" %>');
  $('<%= "#todo_#{@todo.id}" %>').fadeIn('slow', function() {
     ajaxLinks();
   });
});

app/views/todos/edit.html.haml
%h1= t '.title'
%p
  = link_to t('back'), todos_path
  = link_to t('show'), @todo
= render 'form'

app/views/todos/hide.js.erb
$('<%= "#todo_#{@todo.id}" %>').fadeOut('slow');

app/views/todos/index.html.haml
%h1= t('.title')
%p= link_to t('.new_todo'), new_todo_path

%table
  %thead
    %tr
      %th= Todo.human_attribute_name :user_id
      %th= Todo.human_attribute_name :account_id
      %th= Todo.human_attribute_name :completed
      %th= Todo.human_attribute_name :task
      %th{:colspan => 3}= t 'actions'
  
  %tbody
    - for todo in @todos
      %tr{ :class => cycle(:odd, :even) }
        %td= todo.user_id
        %td= todo.account_id
        %td= todo.completed
        %td= todo.task
        %td.action= link_to t('show'), todo
        %td.action= link_to t('edit'), edit_todo_path(todo)
        %td.action= link_to t('destroy'), todo, :confirm => t('are_you_sure'), :method => :delete

app/views/todos/show.html.haml
%h1= t '.title'
%p
  = link_to t('back'), todos_path
  = link_to t('edit'), edit_todo_path(@todo)

%dl
  %dt= Todo.human_attribute_name :user_id
  %dd= @todo.user_id
  %dt= Todo.human_attribute_name :account_id
  %dd= @todo.account_id
  %dt= Todo.human_attribute_name :completed
  %dd= @todo.completed
  %dt= Todo.human_attribute_name :task
  %dd= @todo.task