config/routes.rb
Harmony::Application.routes.draw do

  devise_for :users, :path_names => { :sign_in => 'login', :sign_out => 'logout' }

  resource :profile

  resources :lists do 
    resources :items    
  end  
 
  resources :accounts do
    post 'join', :on => :member
    resources :lists
    resources :notes
    resources :todos do
      member do
        get 'complete'
        get 'hide'
      end
    end
 end

  #match 'accounts/:account_id/todos/:id/complete' => 'todos#complete', :as => :complete_todo
  #match 'accounts/:id/join' => 'accounts#join', :as => :join_account

  match '/' => 'home#index', :as => :home
  root :to => 'home#index'

end

app/models/account.rb
class Account < ActiveRecord::Base

  has_and_belongs_to_many :users 
  has_many :invites, :dependent => :destroy
  has_many :notes, :dependent => :destroy
  has_many :todos, :dependent => :destroy 
  has_many :lists, :dependent => :destroy
  has_many :events, :dependent => :destroy

  def friend(user)
    (self.users - [user]).pop
  end
 
  def harmony?
    self.users.length == 2 
  end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  def index
    @accounts = current_user.accounts

    respond_to do |format|
      format.html
    end
  end

  def show
    @account = Account.find(params[:id])
 
    if @account.users.length < 2
      redirect_to :root, :notice => "Sorry, That Harmony is not Complete, Yet."
    else
      @events = @account.events.order('created_at desc')
      @lists = @account.lists

      @mine = my_unfinished_todos
      @theirs = their_unfinished_todos
      @finished = our_finished_todos

      @notes = @account.notes 
      @friend = @account.friend(current_user)
      respond_to do |format|
        format.html 
      end
    end
  end

  def join 
    @account = Account.find(params[:id])
    @invite = @account.invites.first
    @email = current_user.email 
    if @invite.email == @email
      @account.users << current_user 
      @invite.destroy
      @account.invites == []
      UserMailer.join(@account.friend(current_user), @account).deliver
    end 
    redirect_to @account
  end

  def new
    @account = Account.new

    respond_to do |format|
      format.html 
    end
  end

  def edit
    @account = Account.find(params[:id])
  end

  def create
    @account = Account.new(params[:account])
    @account.name = params[:name] if params[:name]
    @email = params[:email]

    respond_to do |format|
      if @account.save && @email.present?
        @account.users << current_user
        @account.invites << Invite.new(:email => @email)
        UserMailer.invite(@email, current_user, @account).deliver
        format.html { redirect_to(:home, :notice => 'Harmony was created, you can access once the other person accepts.') }
      else
        format.html { render :action => "new" }
      end
    end
  end

  def update
    @account = Account.find(params[:id])

    respond_to do |format|
      if @account.update_attributes(params[:account])
        format.html { redirect_to(@account, :notice => 'Account was successfully updated.') }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  def destroy
    @account = Account.find(params[:id])
    @account.destroy

    respond_to do |format|
      format.html { redirect_to(:home) }
      format.xml  { head :ok }
    end
  end

  private

  def my_unfinished_todos
    return @account.todos.unfinished.for_user(current_user) 
  end

  def their_unfinished_todos
    return @account.todos.unfinished - my_unfinished_todos
  end

  def our_finished_todos
    return @account.todos.finished
  end

end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_account.html.haml
.account
  .name= account.name 
  - if account.harmony? 
    This is an active Harmony with #{account.friend(current_user).name}
  - else 
    This harmony is waiting to be joined by the person you invited.

app/views/accounts/_form.html.haml
.form
  %h3 Account Settings 
  = form_for(@account) do |f|
    - if @account.errors.any?
      #errorExplanation
        %h2= "#{pluralize(@account.errors.count, 'error')} prohibited this user from being saved:"
        %ul
        - @account.errors.full_messages.each do |msg|
          %li= msg
    .label= f.label :name
    .field= f.text_field :name
    .checkbox
      = f.check_box :todo_list_on
      = f.label :todo_list_on
    .checkbox
      = f.check_box :notes_on
      = f.label :notes_on
    .checkbox
      = f.check_box :public
      = f.label :public
    = f.submit :class => :button
  %br.clear

app/views/accounts/_user.html.haml
.card
  .avatar.left= image_tag avatar_url(user)
  %h3.left= user.name

app/views/accounts/edit.html.haml
.account_settings
  %h1 Update Account
  = render 'form'
  = button_to "Delete this account", account_path(@account), 
    :confirm => "\nWARNING: Deleting an account is permanant.\n\nThis will remove the account and all todo items, notes, and other content.\n\nAre you sure?",
    :method => :delete, :class => 'link_button'
  %h3 Account Lists
  = link_to "Create New List", new_account_list_path(@account), :rel => 'facebox'
  %ul
    - @account.lists.each do |list|
      %li
        = list.title
        | 
        = button_to 'Delete List', account_list_path(@account, list), :method => :delete, :class => :link_button
        |
        = link_to 'Rename List', edit_account_list_path(@account, list) 
    

app/views/accounts/index.html.haml
.accounts
  = render :partial => 'account', :collection => @accounts

app/views/accounts/new.html.haml
.form.create_account
  %h3 Create a new account by entering the email address of the person you want to create a harmony with.
  = form_tag('/accounts')
  .label= label_tag 'Name (optional)'
  .field= text_field_tag 'name'
  .label= label_tag 'Email'
  .field= text_field_tag 'email'
  = submit_tag "Create Harmony", :class => :button
  %br.clear 
 

app/views/accounts/show.html.haml
.account
  .info
    .user
      = render :partial => 'user', :locals => { :user => current_user }
    .friend
      = render :partial => 'user', :locals => { :user => @friend }
    %br.clear
  .feed
    %h3 Event Feed
    = link_to 'New Note', new_account_note_path(@account), :rel => 'facebox'
    = render :partial => 'events/event', :collection => @events
  .widgets
    .todos
      %span Things to do.
      = link_to 'I have something you need to do.', new_account_todo_path(@account), :rel => 'facebox'
      #mine= render :partial => 'todos/todo', :collection => @mine, :locals => {:hide => false }
      #theirs= render :partial => 'todos/todo', :collection => @theirs, :locals => {:hide => false }
      #finished= render :partial => 'todos/todo', :collection => @finished, :locals => {:hide => false }
    = render :partial => 'lists/list', :collection => @lists
  %br.clear 